#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE90112A72B05B73A (roderick@argon.org)
#
Name     : perl-String-ShellQuote
Version  : 1.04
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/R/RO/ROSCH/String-ShellQuote-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RO/ROSCH/String-ShellQuote-1.04.tar.gz
Source1  : https://cpan.metacpan.org/authors/id/R/RO/ROSCH/String-ShellQuote-1.04.tar.gz.sig
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-String-ShellQuote-bin = %{version}-%{release}
Requires: perl-String-ShellQuote-man = %{version}-%{release}
Requires: perl-String-ShellQuote-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This distribution contains the String::ShellQuote module, plus a command-line
interface to it.  It contains some functions which are useful for quoting
strings which are going to pass through the shell or a shell-like object.  It
is useful for doing robust tool programming, particularly when dealing with
files whose names contain white space or shell globbing characters.

%package bin
Summary: bin components for the perl-String-ShellQuote package.
Group: Binaries

%description bin
bin components for the perl-String-ShellQuote package.


%package dev
Summary: dev components for the perl-String-ShellQuote package.
Group: Development
Requires: perl-String-ShellQuote-bin = %{version}-%{release}
Provides: perl-String-ShellQuote-devel = %{version}-%{release}
Requires: perl-String-ShellQuote = %{version}-%{release}

%description dev
dev components for the perl-String-ShellQuote package.


%package man
Summary: man components for the perl-String-ShellQuote package.
Group: Default

%description man
man components for the perl-String-ShellQuote package.


%package perl
Summary: perl components for the perl-String-ShellQuote package.
Group: Default
Requires: perl-String-ShellQuote = %{version}-%{release}

%description perl
perl components for the perl-String-ShellQuote package.


%prep
%setup -q -n String-ShellQuote-1.04
cd %{_builddir}/String-ShellQuote-1.04

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/shell-quote

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/String::ShellQuote.3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/shell-quote.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
